[package]
name = "oxided"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
clap = { version = "4.5.43", features = ["derive", "env"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
